#!/bin/bash

PWD="$(pwd)"
BASE_DIR="$PWD"
BCM_DIR="$PWD/bcm2835-1.46"

echo ""
echo "Checking system..."

if [ -d "$BCM_DIR" ]; then
    echo "bcm2835 directory OK..."
fi

sleep 1

echo "Checking required packages..."

sudo apt-get update

dpkg -s g++ 2>/dev/null >/dev/null || sudo apt-get -y install g++
dpkg -s zip 2>/dev/null >/dev/null || sudo apt-get -y install zip
dpkg -s unzip 2>/dev/null >/dev/null || sudo apt-get -y install unzip

echo "Pacakes installed..."
echo "Unzipping libraries, this will take a while..."

cd "$BCM_DIR" && chmod +x configure && ./configure && sudo make && sudo make install

sleep 1

echo ""
echo "Libraries compiled successfully!!! You can now use arduPi in your projects"
echo "Ardupi library is compiled in ardupi directory"
echo ""

exit 0

